import json, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

with open('yes_bias_fade_backtest.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Remove broken cells 20-32
nb['cells'] = nb['cells'][:20]
print(f"Trimmed to {len(nb['cells'])} cells.")

def code_cell(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

def md_cell(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

cell_A = md_cell(
"## Strategy 2: Falling Into Range NO\n\n"
"**Strategy**: Buy NO contracts when YES price falls *into* the 55\u201365\u00a2 range from above.\n\n"
"**Entry condition**: YES price was previously above 0.65, then drops into [0.55, 0.65].  \n"
"No taker-side filter, no slope check \u2014 price direction only.\n\n"
"**Exit**: Hold to settlement (same as Strategy 1).\n\n"
"**Train period**: 2023\u20132024 (fixed 10 contracts)  \n"
"**Test period**: 2025\u20132026 (half-Kelly sizing locked from train)"
)

cell_B = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Signal Generation + Train/Test Split\n"
"#\n"
"# Entry: YES price drops INTO [YES_LOW, YES_HIGH] from above YES_HIGH.\n"
"# One entry per ticker (first qualifying trade), pre-noon local-time filter applied.\n"
"\n"
"from zoneinfo import ZoneInfo as _S2_ZI\n"
"\n"
"\n"
"def build_fall_signal_df() -> pd.DataFrame:\n"
"    \"\"\"Return signals where YES price falls into [YES_LOW, YES_HIGH] from above YES_HIGH.\"\"\"\n"
"    signal_rows = []\n"
"\n"
"    for city, prefix in CITIES.items():\n"
"        trades  = trades_dfs[city].copy()\n"
"        markets = markets_dfs[city][['ticker', 'settlement_value', 'yes_won', 'close_time']].copy()\n"
"        local_tz = _S2_ZI(CITY_TIMEZONES[city])\n"
"\n"
"        city_signals = []\n"
"\n"
"        for ticker, grp in trades.groupby('ticker'):\n"
"            grp = grp.sort_values('created_time').reset_index(drop=True)\n"
"            had_prior_high = False\n"
"            signal_taken   = False\n"
"\n"
"            for _, row in grp.iterrows():\n"
"                if signal_taken:\n"
"                    break\n"
"                yes_p = row['yes_price_dollars']\n"
"\n"
"                if yes_p > YES_HIGH:\n"
"                    had_prior_high = True\n"
"                    continue\n"
"\n"
"                if had_prior_high and YES_LOW <= yes_p <= YES_HIGH:\n"
"                    city_signals.append(row)\n"
"                    signal_taken = True\n"
"\n"
"        if not city_signals:\n"
"            print(f\"{city}: no falling-into-range signals\")\n"
"            continue\n"
"\n"
"        signals = pd.DataFrame(city_signals).reset_index(drop=True)\n"
"\n"
"        # \u2500\u2500 Pre-noon local-time filter \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"        signals['local_hour'] = signals['created_time'].dt.tz_convert(local_tz).dt.hour\n"
"        before_filter = len(signals)\n"
"        signals = signals[signals['local_hour'] < 12].copy()\n"
"        after_filter  = len(signals)\n"
"        print(f\"  {city}: {before_filter - after_filter} signals dropped (post-noon), {after_filter} remain\")\n"
"        signals = signals.drop(columns=['local_hour'])\n"
"\n"
"        if signals.empty:\n"
"            print(f\"{city}: no signals remain after pre-noon filter\")\n"
"            continue\n"
"\n"
"        # \u2500\u2500 Merge settlement data \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"        merged = signals.merge(markets, on='ticker', how='left')\n"
"        merged = merged.dropna(subset=['settlement_value'])\n"
"        if merged.empty:\n"
"            print(f\"{city}: signals found but no settlement data after merge\")\n"
"            continue\n"
"\n"
"        merged['no_won'] = ~merged['yes_won']\n"
"        merged['city']   = city\n"
"        signal_rows.append(merged)\n"
"        print(f\"{city}: {len(merged):4d} falling-into-range signals after all filters\")\n"
"\n"
"    if not signal_rows:\n"
"        raise ValueError(\"No falling-into-range signals found.\")\n"
"\n"
"    df = pd.concat(signal_rows, ignore_index=True)\n"
"    df = df.sort_values('created_time').reset_index(drop=True)\n"
"    return df\n"
"\n"
"\n"
"s2_all_signals = build_fall_signal_df()\n"
"\n"
"# \u2500\u2500 Train / Test split \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"s2_train_signals = s2_all_signals[\n"
"    (s2_all_signals['created_time'] >= TRAIN_START) &\n"
"    (s2_all_signals['created_time'] <  TRAIN_CUTOFF)\n"
"].copy().reset_index(drop=True)\n"
"\n"
"s2_test_signals = s2_all_signals[\n"
"    s2_all_signals['created_time'] >= TRAIN_CUTOFF\n"
"].copy().reset_index(drop=True)\n"
"\n"
"print(f\"\\nTotal signals  : {len(s2_all_signals)}\")\n"
"print(f\"Train signals  : {len(s2_train_signals)}  \"\n"
"      f\"({s2_train_signals['created_time'].min().date()} \u2013 {s2_train_signals['created_time'].max().date()})\")\n"
"print(f\"Test signals   : {len(s2_test_signals)}  \"\n"
"      f\"({s2_test_signals['created_time'].min().date()} \u2013 {s2_test_signals['created_time'].max().date()})\")\n"
)

cell_C = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Train Backtest\n"
"\n"
"s2_train_results = run_backtest(\n"
"    signals          = s2_train_signals,\n"
"    starting_balance = STARTING_BALANCE,\n"
"    fixed_contracts  = TRAIN_CONTRACTS,\n"
"    kelly_fraction   = None,\n"
"    kelly_win_rate   = None,\n"
"    kelly_b          = None,\n"
"    slippage         = SLIPPAGE_CENTS,\n"
"    period_label     = \"S2 TRAIN (2023\u20132024)\",\n"
")\n"
"\n"
"# \u2500\u2500 Derive Kelly parameters from train results \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"s2_train_exec = s2_train_results[s2_train_results['executed'] == True]\n"
"s2_wins       = s2_train_exec[s2_train_exec['no_won'] == True]['net_pnl']\n"
"s2_losses     = s2_train_exec[s2_train_exec['no_won'] == False]['net_pnl']\n"
"\n"
"s2_train_win_rate = s2_train_exec['no_won'].mean() if len(s2_train_exec) > 0 else 0.0\n"
"s2_avg_win        = s2_wins.mean()              if len(s2_wins)   > 0 else 0.0\n"
"s2_avg_loss       = abs(s2_losses.mean())       if len(s2_losses) > 0 else 1e-9\n"
"s2_kelly_b        = s2_avg_win / s2_avg_loss\n"
"\n"
"print(f\"\\nKelly parameters derived from S2 TRAIN period:\")\n"
"print(f\"  Win rate   : {s2_train_win_rate:.4f}\")\n"
"print(f\"  Avg win    : ${s2_avg_win:.4f}\")\n"
"print(f\"  Avg loss   : ${s2_avg_loss:.4f}\")\n"
"print(f\"  b ratio    : {s2_kelly_b:.4f}\")\n"
"s2_raw_kelly = KELLY_FRACTION * (s2_train_win_rate * s2_kelly_b - (1 - s2_train_win_rate)) / s2_kelly_b\n"
"print(f\"  Half-Kelly f*: {s2_raw_kelly:.4f} (fraction of bankroll per trade)\")\n"
)

cell_D = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Train Risk Metrics\n"
"\n"
"s2_train_metrics = compute_risk_metrics(s2_train_results, STARTING_BALANCE, \"S2 TRAIN (2023\u20132024)\")\n"
)

cell_E = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Test Backtest (Kelly sizing locked from train)\n"
"\n"
"s2_raw_kelly_f = KELLY_FRACTION * (s2_train_win_rate * s2_kelly_b - (1 - s2_train_win_rate)) / s2_kelly_b\n"
"if s2_raw_kelly_f <= 0:\n"
"    print(\"WARNING: S2 Kelly fraction <= 0 \u2014 proceeding with MIN_CONTRACTS floor.\")\n"
"\n"
"s2_test_results = run_backtest(\n"
"    signals          = s2_test_signals,\n"
"    starting_balance = STARTING_BALANCE,\n"
"    fixed_contracts  = None,\n"
"    kelly_fraction   = KELLY_FRACTION,\n"
"    kelly_win_rate   = s2_train_win_rate,\n"
"    kelly_b          = s2_kelly_b,\n"
"    slippage         = SLIPPAGE_CENTS,\n"
"    period_label     = \"S2 TEST (2025\u20132026)\",\n"
")\n"
)

cell_F = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Test Risk Metrics\n"
"\n"
"s2_test_metrics = compute_risk_metrics(s2_test_results, STARTING_BALANCE, \"S2 TEST (2025\u20132026)\")\n"
)

cell_G = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Equity Curves\n"
"\n"
"fig, axes = plt.subplots(2, 2, figsize=(15, 10))\n"
"fig.suptitle(\"Falling Into Range NO \u2014 Equity Curves\", fontsize=14, fontweight=\"bold\")\n"
"\n"
"s2_city_colors = {\"LAX\": \"tomato\", \"NY\": \"royalblue\", \"CHI\": \"green\", \"MIA\": \"orange\", \"DEN\": \"purple\"}\n"
"\n"
"# \u2500\u2500 (0,0) Train balance \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"ax = axes[0, 0]\n"
"s2_tr_exec = s2_train_results[s2_train_results[\"executed\"] == True]\n"
"if not s2_tr_exec.empty:\n"
"    ax.plot(s2_tr_exec[\"created_time\"].values,\n"
"            (STARTING_BALANCE + s2_tr_exec[\"net_pnl\"].cumsum()).values,\n"
"            color=\"steelblue\", linewidth=1.5, label=\"Train account balance\")\n"
"ax.axhline(STARTING_BALANCE, color=\"black\", linewidth=0.8, linestyle=\"--\",\n"
"           label=f\"Start ${STARTING_BALANCE:.0f}\")\n"
"ax.set_title(\"S2 TRAIN (2023\u20132024) \u2014 Balance\")\n"
"ax.set_xlabel(\"Date (UTC)\")\n"
"ax.set_ylabel(\"Account Balance ($)\")\n"
"ax.legend(fontsize=8)\n"
"ax.grid(True, alpha=0.3)\n"
"\n"
"# \u2500\u2500 (0,1) Test balance \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"ax = axes[0, 1]\n"
"s2_te_exec = s2_test_results[s2_test_results[\"executed\"] == True]\n"
"if not s2_te_exec.empty:\n"
"    ax.plot(s2_te_exec[\"created_time\"].values,\n"
"            (STARTING_BALANCE + s2_te_exec[\"net_pnl\"].cumsum()).values,\n"
"            color=\"darkorange\", linewidth=1.5, label=\"Test account balance\")\n"
"ax.axhline(STARTING_BALANCE, color=\"black\", linewidth=0.8, linestyle=\"--\",\n"
"           label=f\"Start ${STARTING_BALANCE:.0f}\")\n"
"ax.set_title(\"S2 TEST (2025\u20132026) \u2014 Balance (Kelly Sizing)\")\n"
"ax.set_xlabel(\"Date (UTC)\")\n"
"ax.set_ylabel(\"Account Balance ($)\")\n"
"ax.legend(fontsize=8)\n"
"ax.grid(True, alpha=0.3)\n"
"\n"
"# \u2500\u2500 (1,0) Train P&L by city \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"ax = axes[1, 0]\n"
"for city in CITIES:\n"
"    cdf = s2_tr_exec[s2_tr_exec[\"city\"] == city].sort_values(\"created_time\")\n"
"    if cdf.empty:\n"
"        continue\n"
"    ax.plot(cdf[\"created_time\"].values, cdf[\"net_pnl\"].cumsum().values,\n"
"            label=city, color=s2_city_colors.get(city, \"gray\"), linewidth=1.2)\n"
"ax.axhline(0, color=\"black\", linewidth=0.8, linestyle=\"--\")\n"
"ax.set_title(\"S2 TRAIN (2023\u20132024) \u2014 Cumulative Net P&L by City\")\n"
"ax.set_xlabel(\"Date (UTC)\")\n"
"ax.set_ylabel(\"Cumulative Net P&L ($)\")\n"
"ax.legend(fontsize=8)\n"
"ax.grid(True, alpha=0.3)\n"
"\n"
"# \u2500\u2500 (1,1) Test P&L by city \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
"ax = axes[1, 1]\n"
"for city in CITIES:\n"
"    cdf = s2_te_exec[s2_te_exec[\"city\"] == city].sort_values(\"created_time\")\n"
"    if cdf.empty:\n"
"        continue\n"
"    ax.plot(cdf[\"created_time\"].values, cdf[\"net_pnl\"].cumsum().values,\n"
"            label=city, color=s2_city_colors.get(city, \"gray\"), linewidth=1.2)\n"
"ax.axhline(0, color=\"black\", linewidth=0.8, linestyle=\"--\")\n"
"ax.set_title(\"S2 TEST (2025\u20132026) \u2014 Cumulative Net P&L by City (Kelly Sizing)\")\n"
"ax.set_xlabel(\"Date (UTC)\")\n"
"ax.set_ylabel(\"Cumulative Net P&L ($)\")\n"
"ax.legend(fontsize=8)\n"
"ax.grid(True, alpha=0.3)\n"
"\n"
"plt.tight_layout()\n"
"plt.show()\n"
)

cell_H = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Monte Carlo Simulation (Test Period)\n"
"\n"
"s2_N_SIMS = 1000\n"
"s2_rng    = np.random.default_rng(seed=42)\n"
"\n"
"s2_test_exec_pnl = s2_test_results.loc[s2_test_results[\"executed\"] == True, \"net_pnl\"].values\n"
"s2_n_test_trades = len(s2_test_exec_pnl)\n"
"\n"
"if s2_n_test_trades == 0:\n"
"    print(\"No executed S2 test trades \u2014 skipping Monte Carlo.\")\n"
"else:\n"
"    s2_actual_curve = np.concatenate([[STARTING_BALANCE],\n"
"                                       STARTING_BALANCE + np.cumsum(s2_test_exec_pnl)])\n"
"    s2_actual_curve = np.maximum(s2_actual_curve, 0.0)\n"
"\n"
"    s2_sim_final  = np.empty(s2_N_SIMS)\n"
"    s2_sim_curves = np.empty((s2_N_SIMS, s2_n_test_trades + 1))\n"
"\n"
"    for _s in range(s2_N_SIMS):\n"
"        _sampled  = s2_rng.choice(s2_test_exec_pnl, size=s2_n_test_trades, replace=True)\n"
"        _curve    = np.empty(s2_n_test_trades + 1)\n"
"        _curve[0] = STARTING_BALANCE\n"
"        _ruined   = False\n"
"        for _i, _pnl in enumerate(_sampled):\n"
"            if _ruined:\n"
"                _curve[_i + 1] = 0.0\n"
"            else:\n"
"                _new = _curve[_i] + _pnl\n"
"                if _new <= 0:\n"
"                    _new   = 0.0\n"
"                    _ruined = True\n"
"                _curve[_i + 1] = _new\n"
"        s2_sim_curves[_s] = _curve\n"
"        s2_sim_final[_s]  = _curve[-1]\n"
"\n"
"    s2_p05 = np.percentile(s2_sim_curves, 5,  axis=0)\n"
"    s2_p50 = np.percentile(s2_sim_curves, 50, axis=0)\n"
"    s2_p95 = np.percentile(s2_sim_curves, 95, axis=0)\n"
"\n"
"    x_ax = np.arange(s2_n_test_trades + 1)\n"
"    fig, ax = plt.subplots(figsize=(13, 7))\n"
"    for _s in range(s2_N_SIMS):\n"
"        ax.plot(x_ax, s2_sim_curves[_s], color=\"gray\", alpha=0.05, linewidth=0.5)\n"
"    ax.plot(x_ax, s2_p05, color=\"red\",        linewidth=2.0, label=\"5th percentile\",           zorder=4)\n"
"    ax.plot(x_ax, s2_p50, color=\"darkorange\",  linewidth=2.0, label=\"50th percentile (median)\", zorder=4)\n"
"    ax.plot(x_ax, s2_p95, color=\"green\",       linewidth=2.0, label=\"95th percentile\",          zorder=4)\n"
"    ax.plot(x_ax, s2_actual_curve, color=\"steelblue\", linewidth=2.5, label=\"Actual observed\",   zorder=5)\n"
"    ax.axhline(STARTING_BALANCE, color=\"black\", linewidth=1.0, linestyle=\"--\",\n"
"               label=f\"Starting balance (${STARTING_BALANCE:.0f})\", zorder=3)\n"
"    ax.set_title(\n"
"        f\"S2 Monte Carlo \u2014 TEST 2025\u20132026 ({s2_N_SIMS:,} Simulations, {s2_n_test_trades} Trades Each)\",\n"
"        fontsize=12,\n"
"    )\n"
"    ax.set_xlabel(\"Trade Number\")\n"
"    ax.set_ylabel(\"Account Balance ($)\")\n"
"    ax.legend(fontsize=9, loc=\"upper left\")\n"
"    ax.grid(True, alpha=0.3)\n"
"    plt.tight_layout()\n"
"    plt.show()\n"
"\n"
"    pct_ruined   = (s2_sim_final == 0.0).mean() * 100\n"
"    print(\"=\" * 55)\n"
"    print(\"  S2 MONTE CARLO SUMMARY \u2014 TEST PERIOD (2025\u20132026)\")\n"
"    print(\"=\" * 55)\n"
"    print(f\"  Simulations run       : {s2_N_SIMS:,}\")\n"
"    print(f\"  Trades per simulation : {s2_n_test_trades}\")\n"
"    print(f\"  % simulations ruined  : {pct_ruined:.1f}%\")\n"
"    print(f\"  Median final balance  : ${np.median(s2_sim_final):.2f}\")\n"
"    print(f\"  5th pct final balance : ${np.percentile(s2_sim_final, 5):.2f}\")\n"
"    print(f\"  95th pct final balance: ${np.percentile(s2_sim_final, 95):.2f}\")\n"
"    print(\"=\" * 55)\n"
)

cell_I = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Statistical Significance Tests\n"
"\n"
"run_significance_tests(s2_train_results, \"S2 TRAIN (2023\u20132024)\")\n"
"run_significance_tests(s2_test_results,  \"S2 TEST (2025\u20132026)\")\n"
)

cell_J = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Walk-Forward Optimization\n"
"#\n"
"# 3-month train / 1-month test rolling windows, 1-month step.\n"
"\n"
"import io as _s2_io\n"
"import contextlib as _s2_ctx\n"
"\n"
"s2_min_date = s2_all_signals[\"created_time\"].dt.normalize().min()\n"
"s2_max_date = s2_all_signals[\"created_time\"].dt.normalize().max()\n"
"\n"
"s2_windows = []\n"
"_wf_start = s2_min_date\n"
"while True:\n"
"    _tr_end = _wf_start + pd.DateOffset(months=3)\n"
"    _te_end = _tr_end   + pd.DateOffset(months=1)\n"
"    if _te_end > s2_max_date + pd.Timedelta(days=1):\n"
"        break\n"
"    s2_windows.append((_wf_start, _tr_end, _tr_end, _te_end))\n"
"    _wf_start += pd.DateOffset(months=1)\n"
"\n"
"print(f\"S2 walk-forward: {len(s2_windows)} windows ({s2_min_date.date()} \u2013 {s2_max_date.date()})\")\n"
"\n"
"s2_wf_records = []\n"
"\n"
"for _i, (_tr_s, _tr_e, _te_s, _te_e) in enumerate(s2_windows):\n"
"    print(f\"  Window {_i+1}/{len(s2_windows)}...\", end=\"\\r\")\n"
"    _w_tr = s2_all_signals[\n"
"        (s2_all_signals[\"created_time\"] >= _tr_s) &\n"
"        (s2_all_signals[\"created_time\"] <  _tr_e)\n"
"    ].copy().reset_index(drop=True)\n"
"    _w_te = s2_all_signals[\n"
"        (s2_all_signals[\"created_time\"] >= _te_s) &\n"
"        (s2_all_signals[\"created_time\"] <  _te_e)\n"
"    ].copy().reset_index(drop=True)\n"
"    if len(_w_tr) < 10 or len(_w_te) < 5:\n"
"        continue\n"
"\n"
"    _buf = _s2_io.StringIO()\n"
"    with _s2_ctx.redirect_stdout(_buf):\n"
"        _tr_res = run_backtest(_w_tr, STARTING_BALANCE, TRAIN_CONTRACTS,\n"
"                               None, None, None, SLIPPAGE_CENTS, \"\")\n"
"\n"
"    _tr_exec = _tr_res[_tr_res[\"executed\"] == True]\n"
"    _tr_wr   = _tr_exec[\"no_won\"].mean() if len(_tr_exec) > 0 else 0.0\n"
"    _w_wins  = _tr_exec[_tr_exec[\"no_won\"] == True][\"net_pnl\"]\n"
"    _w_loss  = _tr_exec[_tr_exec[\"no_won\"] == False][\"net_pnl\"]\n"
"    _wkb     = (_w_wins.mean() / abs(_w_loss.mean())\n"
"                if len(_w_wins) > 0 and len(_w_loss) > 0 else 1.0)\n"
"    _wkf     = max(0.0, KELLY_FRACTION * (_tr_wr * _wkb - (1 - _tr_wr)) / _wkb)\n"
"\n"
"    _buf2 = _s2_io.StringIO()\n"
"    with _s2_ctx.redirect_stdout(_buf2):\n"
"        _te_res = run_backtest(_w_te, STARTING_BALANCE, None,\n"
"                               KELLY_FRACTION, _tr_wr, _wkb, SLIPPAGE_CENTS, \"\")\n"
"\n"
"    _te_exec = _te_res[_te_res[\"executed\"] == True]\n"
"    s2_wf_records.append({\n"
"        \"window\":      _i + 1,\n"
"        \"train_start\": _tr_s.date(),\n"
"        \"test_start\":  _te_s.date(),\n"
"        \"test_end\":    _te_e.date(),\n"
"        \"train_n\":     len(_tr_exec),\n"
"        \"test_n\":      len(_te_exec),\n"
"        \"train_wr\":    _tr_wr,\n"
"        \"test_wr\":     _te_exec[\"no_won\"].mean() if len(_te_exec) > 0 else float(\"nan\"),\n"
"        \"kelly_f\":     _wkf,\n"
"        \"test_pnl\":    _te_exec[\"net_pnl\"].sum(),\n"
"    })\n"
"\n"
"print(\"  Walk-forward complete.         \")\n"
"\n"
"s2_wf_df = pd.DataFrame(s2_wf_records)\n"
"if not s2_wf_df.empty:\n"
"    _disp = s2_wf_df.copy()\n"
"    _disp[\"train_wr\"] = _disp[\"train_wr\"].map(\"{:.1%}\".format)\n"
"    _disp[\"test_wr\"]  = _disp[\"test_wr\"].map(lambda x: f\"{x:.1%}\" if pd.notna(x) else \"N/A\")\n"
"    _disp[\"kelly_f\"]  = _disp[\"kelly_f\"].map(\"{:.4f}\".format)\n"
"    _disp[\"test_pnl\"] = _disp[\"test_pnl\"].map(\"${:.2f}\".format)\n"
"    print(\"\\nS2 Walk-Forward Results:\")\n"
"    print(_disp.to_string(index=False))\n"
"\n"
"    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"    fig.suptitle(\"S2 Walk-Forward Optimization\", fontsize=13, fontweight=\"bold\")\n"
"\n"
"    ax = axes[0]\n"
"    _pnls = s2_wf_df[\"test_pnl\"].values\n"
"    ax.bar(s2_wf_df[\"window\"], _pnls,\n"
"           color=[\"green\" if p >= 0 else \"red\" for p in _pnls],\n"
"           edgecolor=\"white\", linewidth=0.5)\n"
"    ax.axhline(0, color=\"black\", linewidth=0.8, linestyle=\"--\")\n"
"    ax.set_title(\"OOS Test Net P&L per Window\")\n"
"    ax.set_xlabel(\"Window #\")\n"
"    ax.set_ylabel(\"Net P&L ($)\")\n"
"    ax.grid(True, alpha=0.3, axis=\"y\")\n"
"\n"
"    ax = axes[1]\n"
"    ax.plot(s2_wf_df[\"window\"], s2_wf_df[\"test_pnl\"].cumsum().values,\n"
"            marker=\"o\", color=\"steelblue\", linewidth=1.8)\n"
"    ax.axhline(0, color=\"black\", linewidth=0.8, linestyle=\"--\")\n"
"    ax.set_title(\"Cumulative OOS Net P&L\")\n"
"    ax.set_xlabel(\"Window #\")\n"
"    ax.set_ylabel(\"Cumulative P&L ($)\")\n"
"    ax.grid(True, alpha=0.3)\n"
"\n"
"    plt.tight_layout()\n"
"    plt.show()\n"
"\n"
"    _pos = (s2_wf_df[\"test_pnl\"] > 0).sum()\n"
"    print(f\"\\n  OOS windows profitable : {_pos}/{len(s2_wf_df)}\")\n"
"    print(f\"  Mean OOS win rate       : {s2_wf_df['test_wr'].dropna().mean():.2%}\")\n"
"    print(f\"  Total OOS P&L           : ${s2_wf_df['test_pnl'].sum():.2f}\")\n"
)

cell_K = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Time-of-Day Distribution\n"
"\n"
"import scipy.stats as _s2_stats_tod\n"
"\n"
"s2_all_tod = pd.concat([\n"
"    s2_train_results[s2_train_results[\"executed\"] == True],\n"
"    s2_test_results[s2_test_results[\"executed\"] == True],\n"
"], ignore_index=True)\n"
"\n"
"if s2_all_tod.empty:\n"
"    print(\"No executed S2 trades \u2014 skipping time-of-day analysis.\")\n"
"else:\n"
"    s2_all_tod[\"hour_utc\"] = s2_all_tod[\"created_time\"].dt.hour\n"
"    s2_hour_counts = s2_all_tod.groupby(\"hour_utc\").size().reindex(range(24), fill_value=0)\n"
"\n"
"    _raw_h   = s2_all_tod[\"hour_utc\"].values\n"
"    _mu, _sg = _s2_stats_tod.norm.fit(_raw_h)\n"
"    _xs      = np.linspace(0, 23, 300)\n"
"    _pdf_sc  = _s2_stats_tod.norm.pdf(_xs, _mu, _sg) * len(_raw_h)\n"
"\n"
"    _norm_c = s2_hour_counts.values / max(s2_hour_counts.values)\n"
"    _colors = [plt.cm.viridis(v) for v in _norm_c]\n"
"\n"
"    fig, ax = plt.subplots(figsize=(12, 5))\n"
"    ax.bar(s2_hour_counts.index, s2_hour_counts.values,\n"
"           color=_colors, edgecolor=\"white\", linewidth=0.5, zorder=2)\n"
"    ax.plot(_xs, _pdf_sc, color=\"tomato\", linewidth=2.0, zorder=3,\n"
"            label=f\"Normal fit (mu={_mu:.1f}h, sigma={_sg:.1f}h)\")\n"
"    ax.set_title(\"S2 \u2014 Time-of-Day Distribution (UTC, Train + Test Combined)\")\n"
"    ax.set_xlabel(\"Hour (UTC)\")\n"
"    ax.set_ylabel(\"Trade Count\")\n"
"    ax.set_xticks(range(24))\n"
"    ax.legend(fontsize=9)\n"
"    ax.grid(True, alpha=0.3, axis=\"y\")\n"
"    plt.tight_layout()\n"
"    plt.show()\n"
"\n"
"    print(f\"Peak trade hour (UTC): {s2_hour_counts.idxmax()}:00\")\n"
"    print(f\"Total executed trades: {len(s2_all_tod)}\")\n"
)

cell_L = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Entry Price Summary Statistics\n"
"\n"
"_s2_ep = s2_test_results[s2_test_results[\"executed\"] == True].copy()\n"
"_s2_ep[\"no_price_paid\"] = _s2_ep[\"actual_entry_no\"]\n"
"\n"
"print(\"=\" * 60)\n"
"print(\"  S2 ENTRY PRICE SUMMARY STATISTICS \u2014 TEST PERIOD\")\n"
"print(\"=\" * 60)\n"
"print()\n"
"print(\"YES price at signal time:\")\n"
"print(_s2_ep[\"yes_price\"].describe().to_string())\n"
"print()\n"
"print(\"NO price paid (actual_entry_no with slippage):\")\n"
"print(_s2_ep[\"no_price_paid\"].describe().to_string())\n"
"print()\n"
"\n"
"_s2_no = _s2_ep[\"no_price_paid\"]\n"
"print(f\"  Mean NO price   : {_s2_no.mean():.4f}\")\n"
"print(f\"  Median NO price : {_s2_no.median():.4f}\")\n"
"print(f\"  Std NO price    : {_s2_no.std():.4f}\")\n"
"print(f\"  Min NO price    : {_s2_no.min():.4f}\")\n"
"print(f\"  Max NO price    : {_s2_no.max():.4f}\")\n"
"print()\n"
"\n"
"_s2_yes  = _s2_ep[\"yes_price\"]\n"
"_s2_n    = len(_s2_yes)\n"
"_s2_bands = [\n"
"    (\"[0.55, 0.58)\", 0.55, 0.58),\n"
"    (\"[0.58, 0.61)\", 0.58, 0.61),\n"
"    (\"[0.61, 0.63)\", 0.61, 0.63),\n"
"    (\"[0.63, 0.65]\", 0.63, 0.651),\n"
"]\n"
"print(\"  YES price sub-band distribution:\")\n"
"for _lbl, _lo, _hi in _s2_bands:\n"
"    _cnt = int(((_s2_yes >= _lo) & (_s2_yes < _hi)).sum())\n"
"    _pct = _cnt / _s2_n * 100 if _s2_n > 0 else 0.0\n"
"    print(f\"    {_lbl}: {_cnt:>4}  ({_pct:.1f}%)\")\n"
"print()\n"
"\n"
"_s2_by_city = _s2_ep.groupby(\"city\")[\"no_price_paid\"].mean().sort_values(ascending=False)\n"
"print(\"  Average entry NO price by city:\")\n"
"for _c, _v in _s2_by_city.items():\n"
"    print(f\"    {_c:<6}: {_v:.4f}\")\n"
"print(\"=\" * 60)\n"
"\n"
"_s2_fig, _s2_axes = plt.subplots(1, 2, figsize=(13, 5))\n"
"_s2_fig.suptitle(\"S2 Entry Price Distribution \u2014 TEST Period\", fontsize=13, fontweight=\"bold\")\n"
"\n"
"_s2_axes[0].hist(_s2_ep[\"yes_price\"].dropna(), bins=10, range=(0.55, 0.65),\n"
"                  color=\"steelblue\", edgecolor=\"white\", linewidth=0.6)\n"
"_s2_axes[0].set_title(\"YES Price at Entry\")\n"
"_s2_axes[0].set_xlabel(\"YES Price\")\n"
"_s2_axes[0].set_ylabel(\"Trade Count\")\n"
"_s2_axes[0].axvline(0.55, color=\"red\", linestyle=\"--\", linewidth=0.9)\n"
"_s2_axes[0].axvline(0.65, color=\"red\", linestyle=\"--\", linewidth=0.9)\n"
"_s2_axes[0].grid(True, alpha=0.3)\n"
"\n"
"_s2_cc = {\"LAX\": \"tomato\", \"NY\": \"royalblue\", \"CHI\": \"green\", \"MIA\": \"orange\", \"DEN\": \"purple\"}\n"
"_s2_axes[1].bar(_s2_by_city.index, _s2_by_city.values,\n"
"                color=[_s2_cc.get(c, \"gray\") for c in _s2_by_city.index],\n"
"                edgecolor=\"white\", linewidth=0.6)\n"
"_s2_axes[1].set_title(\"Avg Entry NO Price by City\")\n"
"_s2_axes[1].set_xlabel(\"City\")\n"
"_s2_axes[1].set_ylabel(\"Avg NO Price Paid ($)\")\n"
"_s2_axes[1].grid(True, alpha=0.3, axis=\"y\")\n"
"\n"
"plt.tight_layout()\n"
"plt.show()\n"
)

cell_M = code_cell(
"# Strategy 2: Falling Into Range NO \u2014 Slippage Sensitivity Analysis\n"
"#\n"
"# Re-run train+test at 5c and 7c slippage, re-deriving Kelly from train at each level.\n"
"\n"
"import contextlib as _s2_ctx2\n"
"import io as _s2_io2\n"
"\n"
"_s2_SLIP_LEVELS = [0.04, 0.05, 0.07]\n"
"_s2_sens_rows   = []\n"
"\n"
"for _slip in _s2_SLIP_LEVELS:\n"
"    _lbl = f\"{int(_slip * 100)}c\"\n"
"\n"
"    _buf = _s2_io2.StringIO()\n"
"    with _s2_ctx2.redirect_stdout(_buf):\n"
"        _tr = run_backtest(s2_train_signals, STARTING_BALANCE, TRAIN_CONTRACTS,\n"
"                           None, None, None, _slip, \"\")\n"
"    _tr_exec = _tr[_tr[\"executed\"] == True]\n"
"    _tr_n    = len(_tr_exec)\n"
"    _tr_wins = _tr_exec[_tr_exec[\"no_won\"] == True][\"net_pnl\"]\n"
"    _tr_loss = _tr_exec[_tr_exec[\"no_won\"] == False][\"net_pnl\"]\n"
"    _tr_pf   = (_tr_wins.sum() / abs(_tr_loss.sum())\n"
"                if len(_tr_loss) > 0 and abs(_tr_loss.sum()) > 0 else float(\"nan\"))\n"
"    _tr_wr   = _tr_exec[\"no_won\"].mean() if _tr_n > 0 else float(\"nan\")\n"
"    _tr_pnl  = _tr_exec[\"net_pnl\"].sum()\n"
"    _s2_sens_rows.append({\"Slippage\": _lbl, \"Period\": \"TRAIN\", \"Trades\": _tr_n,\n"
"                          \"Win Rate\": _tr_wr, \"Net P&L\": _tr_pnl,\n"
"                          \"ROC%\": _tr_pnl / STARTING_BALANCE * 100, \"Profit Factor\": _tr_pf,\n"
"                          \"Avg Edge\": _tr_exec[\"net_pnl\"].mean() if _tr_n > 0 else float(\"nan\")})\n"
"\n"
"    _sw  = _tr_wins.mean() if len(_tr_wins) > 0 else 0.0\n"
"    _sl  = abs(_tr_loss.mean()) if len(_tr_loss) > 0 else 1e-9\n"
"    _skb = _sw / _sl\n"
"    _swr = _tr_wr if pd.notna(_tr_wr) else 0.5\n"
"\n"
"    _buf2 = _s2_io2.StringIO()\n"
"    with _s2_ctx2.redirect_stdout(_buf2):\n"
"        _te = run_backtest(s2_test_signals, STARTING_BALANCE, None,\n"
"                           KELLY_FRACTION, _swr, _skb, _slip, \"\")\n"
"    _te_exec = _te[_te[\"executed\"] == True]\n"
"    _te_n    = len(_te_exec)\n"
"    _te_wins = _te_exec[_te_exec[\"no_won\"] == True][\"net_pnl\"]\n"
"    _te_loss = _te_exec[_te_exec[\"no_won\"] == False][\"net_pnl\"]\n"
"    _te_pf   = (_te_wins.sum() / abs(_te_loss.sum())\n"
"                if len(_te_loss) > 0 and abs(_te_loss.sum()) > 0 else float(\"nan\"))\n"
"    _te_wr   = _te_exec[\"no_won\"].mean() if _te_n > 0 else float(\"nan\")\n"
"    _te_pnl  = _te_exec[\"net_pnl\"].sum()\n"
"    _s2_sens_rows.append({\"Slippage\": _lbl, \"Period\": \"TEST\", \"Trades\": _te_n,\n"
"                          \"Win Rate\": _te_wr, \"Net P&L\": _te_pnl,\n"
"                          \"ROC%\": _te_pnl / STARTING_BALANCE * 100, \"Profit Factor\": _te_pf,\n"
"                          \"Avg Edge\": _te_exec[\"net_pnl\"].mean() if _te_n > 0 else float(\"nan\")})\n"
"\n"
"_s2_sens_df = pd.DataFrame(_s2_sens_rows)\n"
"_s2_sens_df[\"Win Rate\"]      = _s2_sens_df[\"Win Rate\"].map(lambda x: f\"{x:.1%}\" if pd.notna(x) else \"N/A\")\n"
"_s2_sens_df[\"Net P&L\"]       = _s2_sens_df[\"Net P&L\"].map(\"${:.2f}\".format)\n"
"_s2_sens_df[\"ROC%\"]          = _s2_sens_df[\"ROC%\"].map(\"{:.2f}%\".format)\n"
"_s2_sens_df[\"Profit Factor\"]  = _s2_sens_df[\"Profit Factor\"].map(lambda x: f\"{x:.3f}\" if pd.notna(x) else \"N/A\")\n"
"_s2_sens_df[\"Avg Edge\"]       = _s2_sens_df[\"Avg Edge\"].map(lambda x: f\"${x:.4f}\" if pd.notna(x) else \"N/A\")\n"
"\n"
"print(\"=\" * 75)\n"
"print(\"  S2 SLIPPAGE SENSITIVITY ANALYSIS\")\n"
"print(\"=\" * 75)\n"
"print(_s2_sens_df.to_string(index=False))\n"
"print(\"=\" * 75)\n"
"print(\"Note: 4c baseline replicates the main backtest. 5c/7c show degradation.\")\n"
)

new_cells = [cell_A, cell_B, cell_C, cell_D, cell_E, cell_F,
             cell_G, cell_H, cell_I, cell_J, cell_K, cell_L, cell_M]
nb['cells'].extend(new_cells)

with open('yes_bias_fade_backtest.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Saved. Total cells: {len(nb['cells'])}")
for i in range(20, len(nb['cells'])):
    src = ''.join(nb['cells'][i]['source'])
    print(f"  Cell {i} ({nb['cells'][i]['cell_type']}): {src[:80]!r}")
